# credentials.yaml - Updated Structure with Placeholders
# IMPORTANT: Replace placeholder values with your ACTUAL, REGENERATED API keys

# News & Data APIs (Keys you already provided)
# NOTE: Regenerate these keys immediately
reddit:
  serpapi_key: "86fb79358529b65e9fd640d678f3dea38210dd81d669f20536b1ae7946248e86"

twitter:
  serpapi_key: "86fb79358529b65e9fd640d678f3dea38210dd81d669f20536b1ae7946248e86"

cryptopanic:
  api_key: "1ebed1335fcb74080f702fb92c317c5e464ad84e"

alphavantage_key: "ZXKV3VLFMR00619C"

serpapi_key: "86fb79358529b65e9fd640d678f3dea38210dd81d669f20536b1ae7946248e86" # If you have a general SerpApi key

HUGGINGFACE_API_KEY: "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"


